// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createRecordStmt, err = db.PrepareContext(ctx, createRecord); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRecord: %w", err)
	}
	if q.listCastJSONStmt, err = db.PrepareContext(ctx, listCastJSON); err != nil {
		return nil, fmt.Errorf("error preparing query ListCastJSON: %w", err)
	}
	if q.listDirectJSONStmt, err = db.PrepareContext(ctx, listDirectJSON); err != nil {
		return nil, fmt.Errorf("error preparing query ListDirectJSON: %w", err)
	}
	if q.listNestedJSONStmt, err = db.PrepareContext(ctx, listNestedJSON); err != nil {
		return nil, fmt.Errorf("error preparing query ListNestedJSON: %w", err)
	}
	if q.listRecordsStmt, err = db.PrepareContext(ctx, listRecords); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecords: %w", err)
	}
	if q.selectJSONCastsStmt, err = db.PrepareContext(ctx, selectJSONCasts); err != nil {
		return nil, fmt.Errorf("error preparing query SelectJSONCasts: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createRecordStmt != nil {
		if cerr := q.createRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRecordStmt: %w", cerr)
		}
	}
	if q.listCastJSONStmt != nil {
		if cerr := q.listCastJSONStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCastJSONStmt: %w", cerr)
		}
	}
	if q.listDirectJSONStmt != nil {
		if cerr := q.listDirectJSONStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDirectJSONStmt: %w", cerr)
		}
	}
	if q.listNestedJSONStmt != nil {
		if cerr := q.listNestedJSONStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNestedJSONStmt: %w", cerr)
		}
	}
	if q.listRecordsStmt != nil {
		if cerr := q.listRecordsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecordsStmt: %w", cerr)
		}
	}
	if q.selectJSONCastsStmt != nil {
		if cerr := q.selectJSONCastsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing selectJSONCastsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...any) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...any) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...any) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	createRecordStmt    *sql.Stmt
	listCastJSONStmt    *sql.Stmt
	listDirectJSONStmt  *sql.Stmt
	listNestedJSONStmt  *sql.Stmt
	listRecordsStmt     *sql.Stmt
	selectJSONCastsStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		createRecordStmt:    q.createRecordStmt,
		listCastJSONStmt:    q.listCastJSONStmt,
		listDirectJSONStmt:  q.listDirectJSONStmt,
		listNestedJSONStmt:  q.listNestedJSONStmt,
		listRecordsStmt:     q.listRecordsStmt,
		selectJSONCastsStmt: q.selectJSONCastsStmt,
	}
}
