// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
)

type Record struct {
	ID              int32           `json:"id"`
	DataJSON        json.RawMessage `json:"data_json"`
	PreferencesJSON json.RawMessage `json:"preferences_json"`
}

type Review struct {
	ID           int32           `json:"id"`
	RequiredJson json.RawMessage `json:"required_json"`
	OptionalJson json.RawMessage `json:"optional_json"`
}
