// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error)
	ListCastJSON(ctx context.Context) ([]ListCastJSONRow, error)
	ListDirectJSON(ctx context.Context) ([]ListDirectJSONRow, error)
	ListNestedJSON(ctx context.Context) ([]ListNestedJSONRow, error)
	ListRecords(ctx context.Context) ([]Record, error)
	SelectJSONCasts(ctx context.Context) ([]SelectJSONCastsRow, error)
}

var _ Querier = (*Queries)(nil)
