// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"encoding/json"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (id, data_json, preferences_json)
VALUES ($1, $2, $3)
RETURNING id, data_json, preferences_json;
`

type CreateRecordParams struct {
	ID              int32           `json:"id"`
	DataJSON        json.RawMessage `json:"data_json"`
	PreferencesJSON json.RawMessage `json:"preferences_json"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.queryRow(ctx, q.createRecordStmt, createRecord, arg.ID, arg.DataJSON, arg.PreferencesJSON)
	var i Record
	err := row.Scan(&i.ID, &i.DataJSON, &i.PreferencesJSON)
	return i, err
}

const listCastJSON = `-- name: ListCastJSON :many
SELECT id, required_json, optional_json, review_json, plain_text FROM cast_json_view ORDER BY id;
`

type ListCastJSONRow struct {
	ID           int32           `json:"id"`
	RequiredJson json.RawMessage `json:"required_json"`
	OptionalJson json.RawMessage `json:"optional_json"`
	ReviewJson   json.RawMessage `json:"review_json"`
	PlainText    string          `json:"plain_text"`
}

func (q *Queries) ListCastJSON(ctx context.Context) ([]ListCastJSONRow, error) {
	rows, err := q.query(ctx, q.listCastJSONStmt, listCastJSON)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCastJSONRow{}
	for rows.Next() {
		var i ListCastJSONRow
		if err := rows.Scan(
			&i.ID,
			&i.RequiredJson,
			&i.OptionalJson,
			&i.ReviewJson,
			&i.PlainText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectJSON = `-- name: ListDirectJSON :many
SELECT id, required_json, optional_json FROM direct_json_view ORDER BY id;
`

type ListDirectJSONRow struct {
	ID           int32           `json:"id"`
	RequiredJson json.RawMessage `json:"required_json"`
	OptionalJson json.RawMessage `json:"optional_json"`
}

func (q *Queries) ListDirectJSON(ctx context.Context) ([]ListDirectJSONRow, error) {
	rows, err := q.query(ctx, q.listDirectJSONStmt, listDirectJSON)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectJSONRow{}
	for rows.Next() {
		var i ListDirectJSONRow
		if err := rows.Scan(&i.ID, &i.RequiredJson, &i.OptionalJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNestedJSON = `-- name: ListNestedJSON :many
SELECT id, required_json, optional_json, review_json, plain_text FROM nested_json_view ORDER BY id;
`

type ListNestedJSONRow struct {
	ID           int32           `json:"id"`
	RequiredJson json.RawMessage `json:"required_json"`
	OptionalJson json.RawMessage `json:"optional_json"`
	ReviewJson   json.RawMessage `json:"review_json"`
	PlainText    string          `json:"plain_text"`
}

func (q *Queries) ListNestedJSON(ctx context.Context) ([]ListNestedJSONRow, error) {
	rows, err := q.query(ctx, q.listNestedJSONStmt, listNestedJSON)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNestedJSONRow{}
	for rows.Next() {
		var i ListNestedJSONRow
		if err := rows.Scan(
			&i.ID,
			&i.RequiredJson,
			&i.OptionalJson,
			&i.ReviewJson,
			&i.PlainText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, data_json, preferences_json FROM records ORDER BY id;
`

func (q *Queries) ListRecords(ctx context.Context) ([]Record, error) {
	rows, err := q.query(ctx, q.listRecordsStmt, listRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(&i.ID, &i.DataJSON, &i.PreferencesJSON); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectJSONCasts = `-- name: SelectJSONCasts :many
SELECT CAST(required_json AS JSON) AS required_json,
       CAST(optional_json AS JSON) AS optional_json,
       CAST(required_json AS VARCHAR) AS plain_text
FROM reviews;
`

type SelectJSONCastsRow struct {
	RequiredJson json.RawMessage `json:"required_json"`
	OptionalJson json.RawMessage `json:"optional_json"`
	PlainText    string          `json:"plain_text"`
}

func (q *Queries) SelectJSONCasts(ctx context.Context) ([]SelectJSONCastsRow, error) {
	rows, err := q.query(ctx, q.selectJSONCastsStmt, selectJSONCasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectJSONCastsRow{}
	for rows.Next() {
		var i SelectJSONCastsRow
		if err := rows.Scan(&i.RequiredJson, &i.OptionalJson, &i.PlainText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
