// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc devel-claude/database-sql-support-research-hbmwsa@205daf7aeaaa

package authors

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}
