// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc devel-claude/database-sql-support-research-hbmwsa@205daf7aeaaa
// source: batch.go

package authors

import (
	"context"
	"database/sql"
	"errors"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createAuthors = `-- name: CreateAuthors :batchexec
INSERT INTO authors (
  name, bio
) VALUES (
  $1, $2
);
`

type CreateAuthorsBatchResults struct {
	ctx    context.Context
	db     DBTX
	args   []CreateAuthorsParams
	closed bool
}

type CreateAuthorsParams struct {
	Name string
	Bio  sql.NullString
}

func (q *Queries) CreateAuthors(ctx context.Context, arg []CreateAuthorsParams) *CreateAuthorsBatchResults {
	return &CreateAuthorsBatchResults{
		ctx:  ctx,
		db:   q.db,
		args: arg,
	}
}

func (b *CreateAuthorsBatchResults) Exec(f func(int, error)) {
	defer b.Close()
	for t, a := range b.args {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		vals := []any{
			a.Name,
			a.Bio,
		}
		_, err := b.db.ExecContext(b.ctx, createAuthors, vals...)
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateAuthorsBatchResults) Close() error {
	b.closed = true
	return nil
}
