// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"context"
)

type Querier interface {
	InsertAuthor(ctx context.Context, db DBTX, arg []InsertAuthorParams) *InsertAuthorBatchResults
	InsertID(ctx context.Context, db DBTX, id []int32) *InsertIDBatchResults
}

var _ Querier = (*Queries)(nil)
