// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package querytest

import (
	"context"
	"errors"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertAuthor = `-- name: InsertAuthor :batchexec
INSERT INTO authors (id, name) VALUES ($1, $2);
`

type InsertAuthorBatchResults struct {
	ctx    context.Context
	db     DBTX
	q      *Queries
	args   []InsertAuthorParams
	closed bool
}

type InsertAuthorParams struct {
	ID   int32
	Name string
}

func (q *Queries) InsertAuthor(ctx context.Context, arg []InsertAuthorParams) *InsertAuthorBatchResults {
	return &InsertAuthorBatchResults{
		ctx:  ctx,
		db:   q.db,
		q:    q,
		args: arg,
	}
}

func (b *InsertAuthorBatchResults) Exec(f func(int, error)) {
	defer b.Close()
	for t, a := range b.args {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		vals := []any{
			a.ID,
			a.Name,
		}
		_, err := b.q.exec(b.ctx, b.q.insertAuthorStmt, insertAuthor, vals...)
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertAuthorBatchResults) Close() error {
	b.closed = true
	return nil
}

const insertID = `-- name: InsertID :batchexec
INSERT INTO authors (id, name) VALUES ($1, 'unknown');
`

type InsertIDBatchResults struct {
	ctx    context.Context
	db     DBTX
	q      *Queries
	args   []int32
	closed bool
}

func (q *Queries) InsertID(ctx context.Context, id []int32) *InsertIDBatchResults {
	return &InsertIDBatchResults{
		ctx:  ctx,
		db:   q.db,
		q:    q,
		args: id,
	}
}

func (b *InsertIDBatchResults) Exec(f func(int, error)) {
	defer b.Close()
	for t, a := range b.args {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		vals := []any{
			a,
		}
		_, err := b.q.exec(b.ctx, b.q.insertIDStmt, insertID, vals...)
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertIDBatchResults) Close() error {
	b.closed = true
	return nil
}
